version: 2
registries:
  ruby-github:
    type: rubygems-server
    url: https://rubygems.pkg.github.com/paywith/github_api
    token: ${{secrets.GIT_DEPENDABOT_TOKEN}}
updates:

  # Maintain dependencies for ruby, dependabot will review the Gemfile
  - package-ecosystem: "bundler"
    directory: "/"
    registries: "*"
    schedule:
      interval: "daily"

  # Maintain dependencies for npm, dependabot will review the package.json file
  - package-ecosystem: "npm"
    directory: "/"
    registries: "*"
    schedule:
      interval: "daily"

  # Maintain dependencies for docker, dependabot will review the Dockerfile
  - package-ecosystem: "docker"
    directory: "/"
    registries: "*"
    schedule:
      interval: "daily"
