inherit_from: .rubocop_todo.yml

inherit_gem:
  security_tools:
    - config/default.yml

AllCops:
  Exclude:
    - "generators/**/*"
    - "lib/active_merchant/billing/gateways/paypal/**/*"
    - "lib/active_merchant/billing/gateways/paypal_express.rb"
    - "vendor/**/*"
  ExtraDetails: false
  TargetRubyVersion: 2.7
