module ActiveMerchant
  module Billing
    module OrbitalCodes
      CURRENCY_CODES = {
        'DZD' => '012', # Algerian Dinar
          'ARS' => '032', # Argentine Peso
          'AMD' => '051', # Armenian Dram
          'AWG' => '533', # Aruban Guilder
          'AUD' => '036', # Australian Dollar
          'AZN' => '031', # Azerbaijani Manat
          'BSD' => '044', # Bahamian Dollar
          'BDT' => '050', # Bangladeshi Taka
          'BBD' => '052', # Barbados Dollar
          'BYN' => '933', # Belarussian Ruble
          'BZD' => '084', # Belize Dollar
          'BMD' => '060', # Bermudian Dollar
          'BOB' => '068', # Bolivian Boliviano
          'BWP' => '072', # Botswana Pula
          'BRL' => '986', # Brazilian Real
          'GBP' => '826', # British Pound
          'BND' => '096', # Brunei Dollar
          'BGN' => '975', # Bulgarian Lev
          'BIF' => '108', # Burundi Franc
          'XOF' => '952', # CFA Franc BCEAO
          'XAF' => '950', # CFA Franc BEAC
          'XPF' => '953', # CFP Franc
          'CAD' => '124', # Canadian Dollar
          'KHR' => '116', # Cambodian Riel
          'CVE' => '132', # Cape Verdi Escudo
          'KYD' => '136', # Cayman Islands Dollar
          'CLP' => '152', # Chilean Peso
          'CNY' => '156', # Chinese Yuan Renminbi
          'COP' => '170', # Colombian Peso
          'KMF' => '174', # Comoro Franc
          'CRC' => '188', # Costa Rican Colon
          'CZK' => '203', # Czech Koruna
          'DKK' => '208', # Danish Krone
          'DJF' => '262', # Djibouti Franc
          'DOP' => '214', # Dominican Peso
          'XCD' => '951', # East Caribbean Dollar
          'EGP' => '818', # Egyptian Pound
          'SVC' => '222', # El Salvador Colon
          'EEK' => '233', # Estonian Kroon
          'ETB' => '230', # Ethiopian Birr
          'EUR' => '978', # Euro
          'FKP' => '238', # Falkland Islands Pound
          'FJD' => '242', # Fiji Dollar
          'GMD' => '270', # Gambian Dalasi
          'GEL' => '981', # Georgian Lari
          'GHS' => '288', # Ghanaian Cedi
          'GIP' => '292', # Gibraltar Pound
          'GTQ' => '320', # Guatemala Quetzal
          'GNF' => '324', # Guinea Franc
          'GWP' => '624', # Guinea-Bissau Peso
          'GYD' => '328', # Guyanese Dollar
          'HTG' => '332', # Haitian Gourde
          'HNL' => '340', # Honduras Limpera
          'HKD' => '344', # Hong Kong Dollar
          'HUF' => '348', # Hungarian Forint
          'ICK' => '352', # Iceland Krona
          'INR' => '356', # Indian Rupee
          'IDR' => '360', # Indonesian Rupiah
          'ILS' => '376', # Israeli New Shekel
          'JMD' => '388', # Jamaican Dollar
          'JPY' => '392', # Japanese Yen
          'KZT' => '398', # Kazakhstan Tenge
          'KES' => '404', # Kenyan Shilling
          'KGS' => '417', # Kyrgyzstan Som
          'LAK' => '418', # Laos Kip
          'LVL' => '428', # Latvian Lats
          'LBP' => '422', # Lebanese Pound
          'LTL' => '440', # Lithuanian Litas
          'MOP' => '446', # Macau Pataca
          'MGF' => '450', # Malagasy Franc
          'MWK' => '454', # Malawi Kwacha
          'MYR' => '458', # Malaysian Ringgit
          'MVR' => '462', # Maldive Rufiyaa
          'MRO' => '478', # Mauritania Ouguiya
          'MUR' => '480', # Mauritius Rupee
          'MXN' => '484', # Mexican Peso
          'MDL' => '498', # Moldovan Leu
          'MNT' => '496', # Mongolia Tugrik
          'MAD' => '504', # Moroccan Dirham
          'MZN' => '508', # Mozambique Metical
          'NAD' => '516', # Namibia Dollar
          'NPR' => '524', # Nepalese Rupee
          'ANG' => '532', # Netherlands Antillean Guilder
          'PGK' => '598', # New Guinea Kina
          'NZD' => '554', # New Zealand Dollar
          'NIO' => '558', # Nicaraguan Cordoba Oro
          'NGN' => '566', # Nigerian Naira
          'NOK' => '578', # Norwegian Krone
          'PKR' => '586', # Pakistan Rupee
          'PAB' => '590', # Panamanian Balboa
          'PYG' => '600', # Paraguay Guarani
          'PEN' => '604', # Peruvian Nuevo Sol
          'PHP' => '608', # Philippines Peso
          'PLN' => '985', # Polish Zloty
          'QAR' => '634', # Qatari Rial
          'RON' => '946', # Romanian Leu
          'RUB' => '643', # Russian Ruble
          'RWF' => '646', # Rwanda Franc
          'SHP' => '654', # Saint Helena Pound
          'WST' => '882', # Samoan Tala
          'STN' => '678', # Sao Tome & Principe Dobra
          'SAR' => '682', # Saudi Riyal
          'SCR' => '690', # Seychelles Rupee
          'SLL' => '694', # Sierra Leonean Leone
          'SGD' => '702', # Singapore Dollar
          'SBD' => '090', # Solomon Islands Dollar
          'SOS' => '706', # Somali Shilling
          'ZAR' => '710', # South African Rand
          'KRW' => '410', # South Korean Won
          'LKR' => '144', # Sri Lanka Rupee
          'SZL' => '748', # Swaziland Lilangeni
          'SEK' => '752', # Swedish Krona
          'CHF' => '756', # Swiss Franc
          'TWD' => '901', # Taiwan Dollar (New)
          'TZS' => '834', # Tanzanian Shilling
          'THB' => '764', # Thai Baht
          'TOP' => '776', # Tonga Pa'anga
          'TTD' => '780', # Trinidad & Tobago Dollar
          'TRY' => '949', # Turkish Lira (New)
          'UGX' => '800', # Uganda Shilling
          'UAH' => '980', # Ukrainian Hryvnia
          'AED' => '784', # United Arab Emirates Dirham
          'UYU' => '858', # Uruguayan Peso
          'USD' => '840', # U.S. Dollar
          'UZS' => '860', # Uzbekistan Sum
          'VUV' => '548', # Vanuatu Vatu
          'VEB' => '862', # Venezuelan Bolivar
          'VND' => '704', # Vietnamese Dong
          'YER' => '886', # Yemeni Rial
          'ZMK' => '894', # Zambian Kwacha
          'ZWD' => '716'  # Zimbabwe Dollar
      }

      CURRENCY_EXPONENTS = {
        'DZD' => '2', # Algerian Dinar
          'ARS' => '2', # Argentine Peso
          'AMD' => '2', # Armenian Dram
          'AWG' => '2', # Aruban Guilder
          'AUD' => '2', # Australian Dollar
          'AZN' => '2', # Azerbaijani Manat
          'BSD' => '2', # Bahamian Dollar
          'BDT' => '2', # Bangladeshi Taka
          'BBD' => '2', # Barbados Dollar
          'BYN' => '0', # Belarussian Ruble
          'BZD' => '2', # Belize Dollar
          'BMD' => '2', # Bermudian Dollar
          'BOB' => '2', # Bolivian Boliviano
          'BWP' => '2', # Botswana Pula
          'BRL' => '2', # Brazilian Real
          'GBP' => '2', # British Pound
          'BND' => '2', # Brunei Dollar
          'BGN' => '2', # Bulgarian Lev
          'BIF' => '0', # Burundi Franc
          'XOF' => '0', # CFA Franc BCEAO
          'XAF' => '0', # CFA Franc BEAC
          'XPF' => '0', # CFP Franc
          'CAD' => '2', # Canadian Dollar
          'KHR' => '2', # Cambodian Riel
          'CVE' => '2', # Cape Verdi Escudo
          'KYD' => '2', # Cayman Islands Dollar
          'CLP' => '2', # Chilean Peso
          'CNY' => '2', # Chinese Yuan Renminbi
          'COP' => '2', # Colombian Peso
          'KMF' => '0', # Comoro Franc
          'CRC' => '2', # Costa Rican Colon
          'CZK' => '2', # Czech Koruna
          'DKK' => '2', # Danish Krone
          'DJF' => '0', # Djibouti Franc
          'DOP' => '2', # Dominican Peso
          'XCD' => '2', # East Caribbean Dollar
          'EGP' => '2', # Egyptian Pound
          'SVC' => '2', # El Salvador Colon
          'EEK' => '2', # Estonian Kroon
          'ETB' => '2', # Ethiopian Birr
          'EUR' => '2', # Euro
          'FKP' => '2', # Falkland Islands Pound
          'FJD' => '2', # Fiji Dollar
          'GMD' => '2', # Gambian Dalasi
          'GEL' => '2', # Georgian Lari
          'GHS' => '2', # Ghanaian Cedi
          'GIP' => '2', # Gibraltar Pound
          'GTQ' => '2', # Guatemala Quetzal
          'GNF' => '2', # Guinea Franc
          'GWP' => '2', # Guinea-Bissau Peso
          'GYD' => '2', # Guyanese Dollar
          'HTG' => '2', # Haitian Gourde
          'HNL' => '2', # Honduras Limpera
          'HKD' => '2', # Hong Kong Dollar
          'HUF' => '2', # Hungarian Forint
          'ICK' => '2', # Iceland Krona
          'INR' => '2', # Indian Rupee
          'IDR' => '2', # Indonesian Rupiah
          'ILS' => '2', # Israeli New Shekel
          'JMD' => '2', # Jamaican Dollar
          'JPY' => '0', # Japanese Yen
          'KZT' => '2', # Kazakhstan Tenge
          'KES' => '2', # Kenyan Shilling
          'KGS' => '2', # Kyrgyzstan Som
          'LAK' => '0', # Laos Kip
          'LVL' => '2', # Latvian Lats
          'LBP' => '2', # Lebanese Pound
          'LTL' => '2', # Lithuanian Litas
          'MOP' => '2', # Macau Pataca
          'MGF' => '2', # Malagasy Franc
          'MWK' => '2', # Malawi Kwacha
          'MYR' => '2', # Malaysian Ringgit
          'MVR' => '2', # Maldive Rufiyaa
          'MRO' => '2', # Mauritania Ouguiya
          'MUR' => '2', # Mauritius Rupee
          'MXN' => '2', # Mexican Peso
          'MDL' => '2', # Moldovan Leu
          'MNT' => '2', # Mongolia Tugrik
          'MAD' => '2', # Moroccan Dirham
          'MZN' => '2', # Mozambique Metical
          'NAD' => '2', # Namibia Dollar
          'NPR' => '2', # Nepalese Rupee
          'ANG' => '2', # Netherlands Antillean Guilder
          'PGK' => '2', # New Guinea Kina
          'NZD' => '2', # New Zealand Dollar
          'NIO' => '2', # Nicaraguan Cordoba Oro
          'NGN' => '2', # Nigerian Naira
          'NOK' => '2', # Norwegian Krone
          'PKR' => '2', # Pakistan Rupee
          'PAB' => '2', # Panamanian Balboa
          'PYG' => '0', # Paraguay Guarani
          'PEN' => '2', # Peruvian Nuevo Sol
          'PHP' => '2', # Philippines Peso
          'PLN' => '2', # Polish Zloty
          'QAR' => '2', # Qatari Rial
          'RON' => '2', # Romanian Leu
          'RUB' => '2', # Russian Ruble
          'RWF' => '0', # Rwanda Franc
          'SHP' => '2', # Saint Helena Pound
          'WST' => '2', # Samoan Tala
          'STN' => '2', # Sao Tome & Principe Dobra
          'SAR' => '2', # Saudi Riyal
          'SCR' => '2', # Seychelles Rupee
          'SLL' => '2', # Sierra Leonean Leone
          'SGD' => '2', # Singapore Dollar
          'SBD' => '2', # Solomon Islands Dollar
          'SOS' => '2', # Somali Shilling
          'ZAR' => '2', # South African Rand
          'KRW' => '0', # South Korean Won
          'LKR' => '2', # Sri Lanka Rupee
          'SZL' => '2', # Swaziland Lilangeni
          'SEK' => '2', # Swedish Krona
          'CHF' => '2', # Swiss Franc
          'TWD' => '2', # Taiwan Dollar (New)
          'TZS' => '2', # Tanzanian Shilling
          'THB' => '2', # Thai Baht
          'TOP' => '2', # Tonga Pa'anga
          'TTD' => '2', # Trinidad & Tobago Dollar
          'TRY' => '2', # Turkish Lira (New)
          'UGX' => '0', # Uganda Shilling
          'UAH' => '2', # Ukrainian Hryvnia
          'AED' => '2', # United Arab Emirates Dirham
          'UYU' => '2', # Uruguayan Peso
          'USD' => '2', # U.S. Dollar
          'UZS' => '2', # Uzbekistan Sum
          'VUV' => '0', # Vanuatu Vatu
          'VEB' => '2', # Venezuelan Bolivar
          'VND' => '2', # Vietnamese Dong
          'YER' => '2', # Yemeni Rial
          'ZMK' => '2', # Zambian Kwacha
          'ZWD' => '2'  # Zimbabwe Dollar
      }
    end
  end
end
