module ActiveMerchant
  module Billing
    module OrbitalCodes
      CURRENCY_CODES = {
        'AED' => '784',   # United Arab Emirates Dirham
        'AFN' => '971',   # Afghan Afghani
        'AGD' => '951',   # East Caribbean Dollar
        'AMD' => '051'    # Armenian Dram
        'ANG' => '532',   # Netherlands Antillean Guilder
        'ARS' => '032',   # Argentine Peso
        'AUD' => '036',   # Australian Dollar
        'AWG' => '533',   # Aruban Guilder
        'AZN' => '031',   # Azerbaijani Manat
        'BAM' => '977',   # Convertible Marks
        'BBD' => '052',   # Barbados Dollar
        'BDT' => '050',   # Bangladeshi Taka
        'BGN' => '975',   # Bulgarian Lev
        'BHD' => '048',   # Bahraini Dinar
        'BIF' => '108',   # Burundi Franc
        'BMD' => '060',   # Bermudian Dollar
        'BND' => '096',   # Brunei Dollar
        'BOB' => '068',   # Bolivian Boliviano
        'BRL' => '986',   # Brazilian Real
        'BSD' => '044',   # Bahamian Dollar
        'BTN' => '064',   # Bhutanese Ngultrum
        'BWP' => '072',   # Botswana Pula
        'BYR' => '933',   # Belarussian Ruble
        'BZD' => '084',   # Belize Dollar
        'CAD' => '124',   # Canadian Dollar
        'CDF' => '976',   # Congolese Franc
        'CHF' => '756',   # Swiss Franc
        'CLP' => '152',   # Chilean Peso
        'CNY' => '156',   # Chinese Yuan Renminbi
        'COP' => '170',   # Colombian Peso
        'CRC' => '188',   # Costa Rican Colon
        'CUP' => '192',   # Cuban Peso
        'CVE' => '132',   # Cape Verdi Escudo
        'CZK' => '203',   # Czech Koruna
        'DJF' => '262',   # Djibouti Franc
        'DKK' => '208',   # Danish Krone
        'DOP' => '214',   # Dominican Peso
        'DZD' => '012',   # Algerian Dinar
        'EGP' => '818',   # Egyptian Pound
        'ERN' => '232',   # Eritrean Nakfa
        'ETB' => '230',   # Ethiopian Birr
        'EUR' => '978',   # Euro
        'FJD' => '242',   # Fiji Dollar
        'FKP' => '238',   # Falkland Islands Pound
        'GBP' => '826',   # British Pound
        'GEL' => '981',   # Georgian Lari
        'GHS' => '288',   # Ghanaian Cedi
        'GIP' => '292',   # Gibraltar Pound
        'GMD' => '270',   # Gambian Dalasi
        'GNF' => '324',   # Guinea Franc
        'GTQ' => '320',   # Guatemala Quetzal
        'GWP' => '624',   # Guinea-Bissau Peso
        'GYD' => '328',   # Guyanese Dollar
        'HKD' => '344',   # Hong Kong Dollar
        'HNL' => '340',   # Honduras Limpera
        'HRK' => '191',   # Croatian Kuna
        'HTG' => '332',   # Haitian Gourde
        'HUF' => '348',   # Hungarian Forint
        'IDR' => '360',   # Indonesian Rupiah
        'ILS' => '376',   # Israeli New Shekel
        'INR' => '356',   # Indian Rupee
        'IQD' => '368',   # Iraqi Dinar
        'IRR' => '364',   # Iranian Rial
        'ISK' => '352',   # Iceland Krona
        'JMD' => '388',   # Jamaican Dollar
        'JOD' => '400',   # Jordanian Dinar
        'JPY' => '392',   # Japanese Yen
        'KES' => '404',   # Kenyan Shilling
        'KGS' => '417',   # Kyrgyzstan Som
        'KHR' => '116',   # Cambodian Riel
        'KMF' => '174',   # Comoro Franc
        'KPW' => '408',   # North Korean Won
        'KRW' => '410',   # South Korean Won
        'KWD' => '414',   # Kuwaiti Dinar
        'KYD' => '136',   # Cayman Islands Dollar
        'KZT' => '398',   # Kazakhstan Tenge
        'LAK' => '418',   # Laos Kip
        'LBP' => '422',   # Lebanese Pound
        'LKR' => '144',   # Sri Lanka Rupee
        'LRD' => '430',   # Liberian Dollar
        'LSL' => '426',   # Lesotho Loti
        'LTL' => '440',   # Lithuanian Litas
        'LVL' => '428',   # Latvian Lats
        'LYD' => '434',   # Libyan Dinar
        'MAD' => '504',   # Moroccan Dirham
        'MDL' => '498',   # Moldovan Leu
        'MGA' => '969',   # Malagasy Ariary
        'MGF' => '450',   # Madagascar Franc
        'MKD' => '807',   # Macedonian Denar
        'MMK' => '104',   # Myanmar Kyat
        'MNT' => '496',   # Mongolia Tugrik
        'MOP' => '446',   # Macau Pataca
        'MRO' => '478',   # Mauritania Ouguiya
        'MUR' => '480',   # Mauritius Rupee
        'MVR' => '462',   # Maldive Rufiyaa
        'MWK' => '454',   # Malawi Kwacha
        'MXN' => '484',   # Mexican Peso
        'MYR' => '458',   # Malaysian Ringgit
        'MZN' => '508',   # Mozambique Metical
        'NAD' => '516',   # Namibia Dollar
        'NGN' => '566',   # Nigerian Naira
        'NIO' => '558',   # Nicaraguan Cordoba Oro
        'NOK' => '578',   # Norwegian Krone
        'NPR' => '524',   # Nepalese Rupee
        'NZD' => '554',   # New Zealand Dollar
        'OMR' => '512',   # Omani Rial
        'PAB' => '590',   # Panamanian Balboa
        'PEN' => '604',   # Peruvian Nuevo Sol
        'PGK' => '598',   # New Guinea Kina
        'PHP' => '608',   # Philippines Peso
        'PKR' => '586',   # Pakistan Rupee
        'PLN' => '985',   # Polish Zloty
        'PYG' => '600',   # Paraguay Guarani
        'QAR' => '634',   # Qatari Rial
        'RON' => '946',   # Romanian Leu
        'RSD' => '941',   # Serbian Dinar
        'RUB' => '643',   # Russian Ruble
        'RWF' => '646',   # Rwanda Franc
        'SAR' => '682',   # Saudi Riyal
        'SBD' => '090',   # Solomon Islands Dollar
        'SCR' => '690',   # Seychelles Rupee
        'SDG' => '938',   # Sudanese Pound
        'SEK' => '752',   # Swedish Krona
        'SGD' => '702',   # Singapore Dollar
        'SHP' => '654',   # Saint Helena Pound
        'SLL' => '694',   # Sierra Leonean Leone
        'SOS' => '706',   # Somali Shilling
        'SRD' => '968',   # Surinamese Dollar
        'STD' => '678',   # Sao Tome & Principe Dobra
        'SVC' => '222',   # El Salvador Colon
        'SYP' => '760',   # Syrian Pound
        'SZL' => '748',   # Swaziland Lilangeni
        'THB' => '764',   # Thai Baht
        'TJS' => '972',   # Tajikistani Somoni
        'TMT' => '934',   # Turkmenistan Manat
        'TND' => '788',   # Tunisian Dinar
        'TOP' => '776',   # Tonga Pa'anga
        'TRY' => '949',   # Turkish Lira (New)
        'TTD' => '780',   # Trinidad & Tobago Dollar
        'TWD' => '901',   # Taiwan Dollar (New)
        'TZS' => '834',   # Tanzanian Shilling
        'UAH' => '980',   # Ukrainian Hryvnia
        'UGX' => '800',   # Uganda Shilling
        'USD' => '840',   # U.S. Dollar
        'UYU' => '858',   # Uruguayan Peso
        'UZS' => '860',   # Uzbekistan Sum
        'VES' => '928',   # Venezuelan Bolivar
        'VND' => '704',   # Vietnamese Dong
        'VUV' => '548',   # Vanuatu Vatu
        'WST' => '882',   # Samoan Tala
        'XAF' => '950',   # CFA Franc BEAC
        'XAG' => '961',   # Silver
        'XAU' => '959',   # Gold
        'XCD' => '951',   # East Caribbean Dollar
        'XDR' => '960',   # Special Drawing Rights
        'XOF' => '952',   # CFA Franc BCEAO
        'XPD' => '964',   # Palladium
        'XPF' => '953',   # CFP Franc
        'XPT' => '962',   # Platinum
        'YER' => '886',   # Yemeni Rial
        'ZAR' => '710',   # South African Rand
        'ZMK' => '894',   # Zambian Kwacha
        'ZWD' => '716'    # Zimbabwe Dollar
      }

      CURRENCY_EXPONENTS = {
        'AED' => 2,   # United Arab Emirates Dirham
        'AFN' => 2,   # Afghan Afghani
        'AGD' => 2,   # East Caribbean Dollar
        'AMD' => 2,   # Armenian Dram
        'ANG' => 2,   # Netherlands Antillean Guilder
        'ARS' => 2,   # Argentine Peso
        'AUD' => 2,   # Australian Dollar
        'AWG' => 2,   # Aruban Guilder
        'AZN' => 2,   # Azerbaijani Manat
        'BAM' => 2,   # Convertible Marks
        'BBD' => 2,   # Barbados Dollar
        'BDT' => 2,   # Bangladeshi Taka
        'BGN' => 2,   # Bulgarian Lev
        'BHD' => 3,   # Bahraini Dinar
        'BIF' => 0,   # Burundi Franc
        'BMD' => 2,   # Bermudian Dollar
        'BND' => 2,   # Brunei Dollar
        'BOB' => 2,   # Bolivian Boliviano
        'BRL' => 2,   # Brazilian Real
        'BSD' => 2,   # Bahamian Dollar
        'BTN' => 2,   # Bhutanese Ngultrum
        'BWP' => 2,   # Botswana Pula
        'BYR' => 0,   # Belarussian Ruble
        'BZD' => 2,   # Belize Dollar
        'CAD' => 2,   # Canadian Dollar
        'CDF' => 2,   # Congolese Franc
        'CHF' => 2,   # Swiss Franc
        'CLP' => 0,   # Chilean Peso
        'CNY' => 2,   # Chinese Yuan Renminbi
        'COP' => 0,   # Colombian Peso
        'CRC' => 2,   # Costa Rican Colon
        'CUP' => 2,   # Cuban Peso
        'CVE' => 2,   # Cape Verdi Escudo
        'CZK' => 2,   # Czech Koruna
        'DJF' => 0,   # Djibouti Franc
        'DKK' => 2,   # Danish Krone
        'DOP' => 2,   # Dominican Peso
        'DZD' => 2,   # Algerian Dinar
        'EGP' => 2,   # Egyptian Pound
        'ERN' => 2,   # Eritrean Nakfa
        'ETB' => 2,   # Ethiopian Birr
        'EUR' => 2,   # Euro
        'FJD' => 2,   # Fiji Dollar
        'FKP' => 2,   # Falkland Islands Pound
        'GBP' => 2,   # British Pound
        'GEL' => 2,   # Georgian Lari
        'GHS' => 2,   # Ghanaian Cedi
        'GIP' => 2,   # Gibraltar Pound
        'GMD' => 2,   # Gambian Dalasi
        'GNF' => 0,   # Guinea Franc
        'GTQ' => 2,   # Guatemala Quetzal
        'GWP' => 2,   # Guinea-Bissau Peso
        'GYD' => 2,   # Guyanese Dollar
        'HKD' => 2,   # Hong Kong Dollar
        'HNL' => 2,   # Honduras Limpera
        'HRK' => 2,   # Croatian Kuna
        'HTG' => 2,   # Haitian Gourde
        'HUF' => 2,   # Hungarian Forint
        'IDR' => 2,   # Indonesian Rupiah
        'ILS' => 2,   # Israeli New Shekel
        'INR' => 2,   # Indian Rupee
        'IQD' => 3,   # Iraqi Dinar
        'IRR' => 0,   # Iranian Rial
        'ISK' => 0,   # Iceland Krona
        'JMD' => 2,   # Jamaican Dollar
        'JOD' => 3,   # Jordanian Dinar
        'JPY' => 0,   # Japanese Yen
        'KES' => 2,   # Kenyan Shilling
        'KGS' => 2,   # Kyrgyzstan Som
        'KHR' => 2,   # Cambodian Riel
        'KMF' => 0,   # Comoro Franc
        'KPW' => 0,   # North Korean Won
        'KRW' => 0,   # South Korean Won
        'KWD' => 3,   # Kuwaiti Dinar
        'KYD' => 2,   # Cayman Islands Dollar
        'KZT' => 2,   # Kazakhstan Tenge
        'LAK' => 0,   # Laos Kip
        'LBP' => 2,   # Lebanese Pound
        'LKR' => 2,   # Sri Lanka Rupee
        'LRD' => 2,   # Liberian Dollar
        'LSL' => 2,   # Lesotho Loti
        'LTL' => 2,   # Lithuanian Litas
        'LVL' => 2,   # Latvian Lats
        'LYD' => 3,   # Libyan Dinar
        'MAD' => 2,   # Moroccan Dirham
        'MDL' => 2,   # Moldovan Leu
        'MGA' => 1,   # Malagasy Ariary
        'MGF' => 2,   # Madagascar Franc
        'MKD' => 2,   # Macedonian Denar
        'MMK' => 0,   # Myanmar Kyat
        'MNT' => 2,   # Mongolia Tugrik
        'MOP' => 2,   # Macau Pataca
        'MRO' => 2,   # Mauritania Ouguiya
        'MUR' => 2,   # Mauritius Rupee
        'MVR' => 2,   # Maldive Rufiyaa
        'MWK' => 2,   # Malawi Kwacha
        'MXN' => 2,   # Mexican Peso
        'MYR' => 2,   # Malaysian Ringgit
        'MZN' => 2,   # Mozambique Metical
        'NAD' => 2,   # Namibia Dollar
        'NGN' => 2,   # Nigerian Naira
        'NIO' => 2,   # Nicaraguan Cordoba Oro
        'NOK' => 2,   # Norwegian Krone
        'NPR' => 2,   # Nepalese Rupee
        'NZD' => 2,   # New Zealand Dollar
        'OMR' => 3,   # Omani Rial
        'PAB' => 2,   # Panamanian Balboa
        'PEN' => 2,   # Peruvian Nuevo Sol
        'PGK' => 2,   # New Guinea Kina
        'PHP' => 2,   # Philippines Peso
        'PKR' => 2,   # Pakistan Rupee
        'PLN' => 2,   # Polish Zloty
        'PYG' => 0,   # Paraguay Guarani
        'QAR' => 2,   # Qatari Rial
        'RON' => 2,   # Romanian Leu
        'RSD' => 2,   # Serbian Dinar
        'RUB' => 2,   # Russian Ruble
        'RWF' => 0,   # Rwanda Franc
        'SAR' => 2,   # Saudi Riyal
        'SBD' => 2,   # Solomon Islands Dollar
        'SCR' => 2,   # Seychelles Rupee
        'SDG' => 2,   # Sudanese Pound
        'SEK' => 2,   # Swedish Krona
        'SGD' => 2,   # Singapore Dollar
        'SHP' => 2,   # Saint Helena Pound
        'SLL' => 2,   # Sierra Leonean Leone
        'SOS' => 2,   # Somali Shilling
        'SRD' => 2,   # Surinamese Dollar
        'STD' => 2,   # Sao Tome & Principe Dobra
        'SVC' => 2,   # El Salvador Colon
        'SYP' => 2,   # Syrian Pound
        'SZL' => 2,   # Swaziland Lilangeni
        'THB' => 2,   # Thai Baht
        'TJS' => 2,   # Tajikistani Somoni
        'TMT' => 2,   # Turkmenistan Manat
        'TND' => 3,   # Tunisian Dinar
        'TOP' => 2,   # Tonga Pa'anga
        'TRY' => 2,   # Turkish Lira (New)
        'TTD' => 2,   # Trinidad & Tobago Dollar
        'TWD' => 2,   # Taiwan Dollar (New)
        'TZS' => 2,   # Tanzanian Shilling
        'UAH' => 2,   # Ukrainian Hryvnia
        'UGX' => 0,   # Uganda Shilling
        'USD' => 2,   # U.S. Dollar
        'UYU' => 2,   # Uruguayan Peso
        'UZS' => 2,   # Uzbekistan Sum
        'VES' => 2,   # Venezuelan Bolivar
        'VND' => 0,   # Vietnamese Dong
        'VUV' => 0,   # Vanuatu Vatu
        'WST' => 2,   # Samoan Tala
        'XAF' => 0,   # CFA Franc BEAC
        'XAG' => 0,   # Silver
        'XAU' => 0,   # Gold
        'XCD' => 2,   # East Caribbean Dollar
        'XDR' => 0,   # Special Drawing Rights
        'XOF' => 0,   # CFA Franc BCEAO
        'XPD' => 0,   # Palladium
        'XPF' => 0,   # CFP Franc
        'XPT' => 0,   # Platinum
        'YER' => 2,   # Yemeni Rial
        'ZAR' => 2,   # South African Rand
        'ZMK' => 2,   # Zambian Kwacha
        'ZWD' => 2    # Zimbabwe Dollar
      }
    end
  end
end
